version: '3.8'

services:
  app:
    build: .
    command: python main.py
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: warehouse
    ports:
      - "5432:5432"